### ISSUE TITLE
ModuleNotFoundError: No module named 'dynamic_point_pool_ext'

### ISSUE THREAD

**Issue by Baymax1520301** [BraveGroup/FullySparseFusion#3]
Traceback (most recent call last):
  File "./tools/test.py", line 248, in <module>
    main()
  File "./tools/test.py", line 140, in main
    plg_lib = importlib.import_module(_module_path)
  File "/home/bjw/miniconda3/envs/FSF/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/bjw/workspace/FullySparseFusion/projects/mmdet3d_plugin/__init__.py", line 8, in <module>
    from .models.backbones import *
  File "/home/bjw/workspace/FullySparseFusion/projects/mmdet3d_plugin/models/backbones/__init__.py", line 1, in <module>
    from .sir import SIR
  File "/home/bjw/workspace/FullySparseFusion/projects/mmdet3d_plugin/models/backbones/sir.py", line 7, in <module>
    from projects.mmdet3d_plugin.ops import scatter_v2
  File "/home/bjw/workspace/FullySparseFusion/projects/mmdet3d_plugin/ops/__init__.py", line 1, in <module>
    from .dynamic_point_pool_op import dynamic_point_pool
  File "/home/bjw/workspace/FullySparseFusion/projects/mmdet3d_plugin/ops/dynamic_point_pool_op.py", line 6, in <module>
    import dynamic_point_pool_ext
ModuleNotFoundError: No module named 'dynamic_point_pool_ext'

**Comment by liyingyanUCAS** [comment]
Thank you for your attention,  we will update a detailed installation guide within two weeks. Stay tuned!

**Comment by Baymax1520301** [comment]
好的，谢谢

**Comment by liyingyanUCAS** [comment]
Hi, I have updated the installation guide, if you have further issues with the installation, you can send e-mails to me: liyingyan2021@ia.ac.cn

**Comment by Baymax1520301** [comment]
> Hi, I have updated the installation guide, if you have further issues with the installation, you can send e-mails to me: [liyingyan2021@ia.ac.cn](mailto:liyingyan2021@ia.ac.cn

Thank you for your help. I will try later.
